package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author LENOVO
 */


import entity.Balok;
import entity.Bola;
import entity.Kerucut;
import entity.Kubus;
import entity.Tabung;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jInternalFrameBalok.setSize(390,309);
        jInternalFrameBalok.setVisible(false);
        jInternalFrameKubus.setSize(390,309);
        jInternalFrameKubus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBalok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButtonKubus = new javax.swing.JButton();
        jDekstopPaneSM1 = new gui.JDekstopPaneSM();
        jInternalFrameBalok = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPanjang = new javax.swing.JTextField();
        jTextFieldLebar = new javax.swing.JTextField();
        jTextFieldTinggi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jInternalFrameKubus = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSisiKubus = new javax.swing.JTextField();
        jButtonVolKubus = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jInternalFrameTabung = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldJariTabung = new javax.swing.JTextField();
        jTextFieldTinggiTabung = new javax.swing.JTextField();
        jButtonVolTabung = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jInternalFrameKerucut = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldJariKerucut = new javax.swing.JTextField();
        jTextFieldTinggiKerucut = new javax.swing.JTextField();
        jButtonVolKerucut = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jInternalFrameBola = new javax.swing.JInternalFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldJariBola = new javax.swing.JTextField();
        jButtonVolBola = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlHighlight);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setForeground(new java.awt.Color(255, 153, 102));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(662, 680));

        jPanel2.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setForeground(java.awt.SystemColor.controlDkShadow);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel1.setText("PERHITUNGAN VOLUME BANGUN RUANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButtonBalok.setBackground(java.awt.SystemColor.controlHighlight);
        jButtonBalok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonBalok.setForeground(java.awt.SystemColor.controlDkShadow);
        jButtonBalok.setText("Balok");
        jButtonBalok.setToolTipText("Volume Balok");
        jButtonBalok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBalok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBalok.setFocusable(false);
        jButtonBalok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBalok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalokActionPerformed(evt);
            }
        });

        jButtonKubus.setBackground(java.awt.SystemColor.controlHighlight);
        jButtonKubus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonKubus.setForeground(java.awt.SystemColor.controlDkShadow);
        jButtonKubus.setText("Kubus");
        jButtonKubus.setToolTipText("Volume Balok");
        jButtonKubus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonKubus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKubus.setFocusable(false);
        jButtonKubus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonKubus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKubusActionPerformed(evt);
            }
        });

        jInternalFrameBalok.setClosable(true);
        jInternalFrameBalok.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameBalok.setIconifiable(true);
        jInternalFrameBalok.setMaximizable(true);
        jInternalFrameBalok.setResizable(true);
        jInternalFrameBalok.setTitle("BALOK");
        jInternalFrameBalok.setVisible(true);
        jInternalFrameBalok.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameBalokInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameBalokInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameBalokInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Volume Balok"));

        jLabel5.setText("Panjang :");

        jLabel2.setText("Lebar     :");

        jLabel3.setText("Tinggi     :");

        jTextFieldPanjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPanjangKeyPressed(evt);
            }
        });

        jTextFieldLebar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLebarKeyPressed(evt);
            }
        });

        jTextFieldTinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTinggiKeyPressed(evt);
            }
        });

        jButton1.setText("Hitung Volume");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel11.setText("Volume : Panjang x Lebar x Tinggi");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPanjang))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTinggi))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLebar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrameBalokLayout = new javax.swing.GroupLayout(jInternalFrameBalok.getContentPane());
        jInternalFrameBalok.getContentPane().setLayout(jInternalFrameBalokLayout);
        jInternalFrameBalokLayout.setHorizontalGroup(
            jInternalFrameBalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBalokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrameBalokLayout.setVerticalGroup(
            jInternalFrameBalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBalokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDekstopPaneSM1.add(jInternalFrameBalok);
        jInternalFrameBalok.setBounds(0, 0, 440, 405);

        jInternalFrameKubus.setClosable(true);
        jInternalFrameKubus.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameKubus.setIconifiable(true);
        jInternalFrameKubus.setMaximizable(true);
        jInternalFrameKubus.setResizable(true);
        jInternalFrameKubus.setTitle("KUBUS");
        jInternalFrameKubus.setVisible(true);
        jInternalFrameKubus.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameKubusInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameKubusInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Volume Kubus"));

        jLabel4.setText("Panjang ketiga sisi :");

        jTextFieldSisiKubus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSisiKubusKeyPressed(evt);
            }
        });

        jButtonVolKubus.setText("Hitung Volume");
        jButtonVolKubus.setToolTipText("Hitung Volume");
        jButtonVolKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolKubusActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel10.setText("Volume : Sisi x Sisi x Sisi");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSisiKubus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVolKubus)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSisiKubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVolKubus)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrameKubusLayout = new javax.swing.GroupLayout(jInternalFrameKubus.getContentPane());
        jInternalFrameKubus.getContentPane().setLayout(jInternalFrameKubusLayout);
        jInternalFrameKubusLayout.setHorizontalGroup(
            jInternalFrameKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameKubusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrameKubusLayout.setVerticalGroup(
            jInternalFrameKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameKubusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDekstopPaneSM1.add(jInternalFrameKubus);
        jInternalFrameKubus.setBounds(0, 0, 394, 413);

        jPanel5.setBackground(java.awt.SystemColor.controlHighlight);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jDekstopPaneSM1.add(jPanel5);
        jPanel5.setBounds(0, 0, 540, 410);

        jInternalFrameTabung.setClosable(true);
        jInternalFrameTabung.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameTabung.setIconifiable(true);
        jInternalFrameTabung.setMaximizable(true);
        jInternalFrameTabung.setResizable(true);
        jInternalFrameTabung.setTitle("TABUNG");
        jInternalFrameTabung.setVisible(true);
        jInternalFrameTabung.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameTabungInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Volume Tabung"));

        jLabel6.setText("Jari - jari (r)    :");

        jLabel7.setText("Tinggi              :");

        jTextFieldJariTabung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldJariTabungKeyPressed(evt);
            }
        });

        jTextFieldTinggiTabung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTinggiTabungKeyPressed(evt);
            }
        });

        jButtonVolTabung.setText("Hitung Volume");
        jButtonVolTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolTabungActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel12.setText("Volume : Phi(3,14) x r x r x Tinggi");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVolTabung))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldJariTabung)
                            .addComponent(jTextFieldTinggiTabung))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldJariTabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTinggiTabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVolTabung)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrameTabungLayout = new javax.swing.GroupLayout(jInternalFrameTabung.getContentPane());
        jInternalFrameTabung.getContentPane().setLayout(jInternalFrameTabungLayout);
        jInternalFrameTabungLayout.setHorizontalGroup(
            jInternalFrameTabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTabungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrameTabungLayout.setVerticalGroup(
            jInternalFrameTabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTabungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDekstopPaneSM1.add(jInternalFrameTabung);
        jInternalFrameTabung.setBounds(0, 0, 401, 248);

        jInternalFrameKerucut.setClosable(true);
        jInternalFrameKerucut.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameKerucut.setIconifiable(true);
        jInternalFrameKerucut.setMaximizable(true);
        jInternalFrameKerucut.setResizable(true);
        jInternalFrameKerucut.setTitle("KERUCUT");
        jInternalFrameKerucut.setVisible(true);
        jInternalFrameKerucut.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameKerucutInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Volume Kerucut"));

        jLabel8.setText("Jari - jari (r)    :");

        jLabel9.setText("Tinggi              :");

        jTextFieldJariKerucut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldJariKerucutKeyPressed(evt);
            }
        });

        jTextFieldTinggiKerucut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTinggiKerucutKeyPressed(evt);
            }
        });

        jButtonVolKerucut.setText("Hitung Volume");
        jButtonVolKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolKerucutActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel13.setText("Volume : 1/3*(Phi(3,14) x r x r x Tinggi)");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldJariKerucut))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTinggiKerucut))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addComponent(jButtonVolKerucut))
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldJariKerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTinggiKerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVolKerucut)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrameKerucutLayout = new javax.swing.GroupLayout(jInternalFrameKerucut.getContentPane());
        jInternalFrameKerucut.getContentPane().setLayout(jInternalFrameKerucutLayout);
        jInternalFrameKerucutLayout.setHorizontalGroup(
            jInternalFrameKerucutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameKerucutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrameKerucutLayout.setVerticalGroup(
            jInternalFrameKerucutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameKerucutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDekstopPaneSM1.add(jInternalFrameKerucut);
        jInternalFrameKerucut.setBounds(0, 0, 458, 477);

        jInternalFrameBola.setClosable(true);
        jInternalFrameBola.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameBola.setIconifiable(true);
        jInternalFrameBola.setMaximizable(true);
        jInternalFrameBola.setResizable(true);
        jInternalFrameBola.setTitle("BOLA");
        jInternalFrameBola.setVisible(true);
        jInternalFrameBola.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameBolaInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Volume Bola"));

        jLabel14.setText("Jari - jari (r)    :");

        jTextFieldJariBola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldJariBolaKeyPressed(evt);
            }
        });

        jButtonVolBola.setText("HitungVolume");
        jButtonVolBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolBolaActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel15.setText("Volume : Phi(3,14) x r x r x r");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldJariBola))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVolBola))
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldJariBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVolBola)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrameBolaLayout = new javax.swing.GroupLayout(jInternalFrameBola.getContentPane());
        jInternalFrameBola.getContentPane().setLayout(jInternalFrameBolaLayout);
        jInternalFrameBolaLayout.setHorizontalGroup(
            jInternalFrameBolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrameBolaLayout.setVerticalGroup(
            jInternalFrameBolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDekstopPaneSM1.add(jInternalFrameBola);
        jInternalFrameBola.setBounds(0, 0, 418, 242);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tabung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Kerucut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Bola");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBalok, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKubus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jDekstopPaneSM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jButtonKubus, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jDekstopPaneSM1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalokActionPerformed

        jInternalFrameBalok.setVisible(true);

        try {
            // TODO add your handling code here:
            jInternalFrameBalok.setIcon(false);
            jInternalFrameBalok.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBalokActionPerformed

    private void jButtonKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKubusActionPerformed
        // TODO add your handling code here:
        
        jInternalFrameKubus.setVisible(true);
        try {
                      
            // TODO add your handling code here:
            jInternalFrameKubus.setIcon(false);  
            jInternalFrameKubus.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonKubusActionPerformed

    private void jTextFieldPanjangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPanjangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTextFieldLebar.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldPanjangKeyPressed

    private void jTextFieldLebarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLebarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTextFieldTinggi.requestFocus();
        }else if(evt.getKeyCode()== KeyEvent.VK_UP){
            jTextFieldPanjang.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldLebarKeyPressed

    private void jTextFieldTinggiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTinggiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP){
            jTextFieldLebar.requestFocus();
        }else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldTinggiKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (jTextFieldPanjang.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Panjang masih kosong !");
            jTextFieldPanjang.requestFocus();
        }else if (jTextFieldLebar.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Lebar masih kosong !");
            jTextFieldLebar.requestFocus();
        }
        else if(jTextFieldTinggi.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Tinggi masih kosong !");
            jTextFieldTinggi.requestFocus();
        }
        else{
            try{

                Balok balok = new Balok();
                balok.setPanjang(Double.parseDouble(jTextFieldPanjang.getText()));
                balok.setLebar(Double.parseDouble(jTextFieldLebar.getText()));
                balok.setTinggi(Double.parseDouble(jTextFieldTinggi.getText()));

                balok.cetak();

            }catch(NumberFormatException ex){
                JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Inputkanlah angka !\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jInternalFrameBalokInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameBalokInternalFrameDeactivated
        // TODO add your handling code here:
        if (jInternalFrameBalok.isVisible()){
        }else{
            jTextFieldPanjang.setText("");
            jTextFieldLebar.setText("");
            jTextFieldTinggi.setText("");
        }
    }//GEN-LAST:event_jInternalFrameBalokInternalFrameDeactivated

    private void jInternalFrameBalokInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameBalokInternalFrameDeiconified

    }//GEN-LAST:event_jInternalFrameBalokInternalFrameDeiconified

    private void jInternalFrameBalokInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameBalokInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameBalokInternalFrameOpened

    private void jTextFieldSisiKubusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSisiKubusKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonVolKubusActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldSisiKubusKeyPressed

    private void jButtonVolKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolKubusActionPerformed
        // TODO add your handling code here:
        if(jTextFieldSisiKubus.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Sisi masih kosong !");
        }
        else{
            try{
                Kubus kubus = new Kubus();
                kubus.setSisi(Double.parseDouble(jTextFieldSisiKubus.getText()));

                kubus.cetak();

            }catch(NumberFormatException ex){
                JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Inputkanlah angka !\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonVolKubusActionPerformed

    private void jInternalFrameKubusInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameKubusInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameKubusInternalFrameClosed

    private void jInternalFrameKubusInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameKubusInternalFrameDeactivated

        if (jInternalFrameKubus.isVisible()){
        }else{
            jTextFieldSisiKubus.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameKubusInternalFrameDeactivated

    private void jTextFieldJariTabungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldJariTabungKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTextFieldTinggiTabung.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldJariTabungKeyPressed

    private void jTextFieldTinggiTabungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTinggiTabungKeyPressed
        // TODO add your handling code here: if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (evt.getKeyCode() == KeyEvent.VK_UP){
                jTextFieldJariTabung.requestFocus();
            }else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                jButtonVolTabungActionPerformed(null);
            }
    }//GEN-LAST:event_jTextFieldTinggiTabungKeyPressed

    private void jButtonVolTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolTabungActionPerformed
        // TODO add your handling code here:
        if (jTextFieldJariTabung.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Jari - jari masih kosong !");
            jTextFieldJariTabung.requestFocus();
        }else if (jTextFieldTinggiTabung.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Tinggi masih kosong !");
            jTextFieldTinggiTabung.requestFocus();
        }

        else{
            try{
                Tabung tabung = new Tabung();
                tabung.setJari_jari(Double.parseDouble(jTextFieldJariTabung.getText()));
                tabung.setTinggi(Double.parseDouble(jTextFieldTinggiTabung.getText()));

                tabung.cetak();

            }catch(NumberFormatException ex){
                JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Inputkanlah angka !\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonVolTabungActionPerformed

    private void jInternalFrameTabungInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameTabungInternalFrameDeactivated
        // TODO add your handling code here:
        if (jInternalFrameTabung.isVisible()){
        }else{
            jTextFieldJariTabung.setText("");
            jTextFieldTinggiTabung.setText("");
        }
    }//GEN-LAST:event_jInternalFrameTabungInternalFrameDeactivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          jInternalFrameTabung.setVisible(true);
        try {
                      
            // TODO add your handling code here:
            jInternalFrameTabung.setIcon(false);  
            jInternalFrameTabung.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldJariKerucutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldJariKerucutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            jTextFieldTinggiKerucut.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldJariKerucutKeyPressed

    private void jTextFieldTinggiKerucutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTinggiKerucutKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_UP){
            jTextFieldJariKerucut.requestFocus();
        }else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonVolKerucutActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldTinggiKerucutKeyPressed

    private void jButtonVolKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolKerucutActionPerformed
        // TODO add your handling code here:
        if (jTextFieldJariKerucut.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Jari - jari masih kosong !");
            jTextFieldJariKerucut.requestFocus();
        }else if (jTextFieldTinggiKerucut.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Tinggi masih kosong !");
            jTextFieldTinggiKerucut.requestFocus();
        }

        else{
            try{
                Kerucut kerucut = new Kerucut();
                kerucut.setJari_jari(Double.parseDouble(jTextFieldJariKerucut.getText()));
                kerucut.setTinggi(Double.parseDouble(jTextFieldTinggiKerucut.getText()));

                kerucut.cetak();

            }catch(NumberFormatException ex){
                JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Inputkanlah angka !\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonVolKerucutActionPerformed

    private void jInternalFrameKerucutInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameKerucutInternalFrameDeactivated
        if (jInternalFrameKerucut.isVisible()){
        }else{
            jTextFieldJariKerucut.setText("");
            jTextFieldTinggiKerucut.setText("");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameKerucutInternalFrameDeactivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          jInternalFrameKerucut.setVisible(true);
        try {
                      
            // TODO add your handling code here:
            jInternalFrameKerucut.setIcon(false);  
            jInternalFrameKerucut.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldJariBolaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldJariBolaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonVolBolaActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldJariBolaKeyPressed

    private void jButtonVolBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolBolaActionPerformed
        // TODO add your handling code here:
        if(jTextFieldJariBola.getText().equals("")){
            JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Sisi masih kosong !");
        }
        else{
            try{
                Bola bola = new Bola();
                bola.setJari_jari(Double.parseDouble(jTextFieldJariBola.getText()));
                bola.cetak();

            }catch(NumberFormatException ex){
                JOptionPane.showInternalMessageDialog(jDekstopPaneSM1,"Inputkanlah angka !\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonVolBolaActionPerformed

    private void jInternalFrameBolaInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameBolaInternalFrameDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameBolaInternalFrameDeactivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           jInternalFrameBola.setVisible(true);
        try {
                      
            // TODO add your handling code here:
            jInternalFrameBola.setIcon(false);  
            jInternalFrameBola.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBalok;
    private javax.swing.JButton jButtonKubus;
    private javax.swing.JButton jButtonVolBola;
    private javax.swing.JButton jButtonVolKerucut;
    private javax.swing.JButton jButtonVolKubus;
    private javax.swing.JButton jButtonVolTabung;
    private gui.JDekstopPaneSM jDekstopPaneSM1;
    private javax.swing.JInternalFrame jInternalFrameBalok;
    private javax.swing.JInternalFrame jInternalFrameBola;
    private javax.swing.JInternalFrame jInternalFrameKerucut;
    private javax.swing.JInternalFrame jInternalFrameKubus;
    private javax.swing.JInternalFrame jInternalFrameTabung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldJariBola;
    private javax.swing.JTextField jTextFieldJariKerucut;
    private javax.swing.JTextField jTextFieldJariTabung;
    private javax.swing.JTextField jTextFieldLebar;
    private javax.swing.JTextField jTextFieldPanjang;
    private javax.swing.JTextField jTextFieldSisiKubus;
    private javax.swing.JTextField jTextFieldTinggi;
    private javax.swing.JTextField jTextFieldTinggiKerucut;
    private javax.swing.JTextField jTextFieldTinggiTabung;
    // End of variables declaration//GEN-END:variables
}
